# Activity categories
CATEGORY_SIGHTSEEING = "sightseeing"
CATEGORY_FOOD = "food"
CATEGORY_SHOPPING = "shopping"
CATEGORY_TRANSPORTATION = "transportation"
CATEGORY_ACCOMMODATION = "accommodation"
CATEGORY_ENTERTAINMENT = "entertainment"
CATEGORY_OTHER = "other"

VALID_CATEGORIES = [
    CATEGORY_SIGHTSEEING,
    CATEGORY_FOOD,
    CATEGORY_SHOPPING,
    CATEGORY_TRANSPORTATION,
    CATEGORY_ACCOMMODATION,
    CATEGORY_ENTERTAINMENT,
    CATEGORY_OTHER,
]


# Error codes
class ErrorCode:
    """Activity-related error codes."""
    ACTIVITY_NOT_FOUND = "ACTIVITY_NOT_FOUND"
    NOT_ACTIVITY_OWNER = "NOT_ACTIVITY_OWNER"
    INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
    ACTIVITY_DATE_OUT_OF_ITINERARY = "ACTIVITY_DATE_OUT_OF_ITINERARY"
    INVALID_TIME_RANGE = "INVALID_TIME_RANGE"
    INVALID_ORDER_INDEX = "INVALID_ORDER_INDEX"
    CANNOT_MODIFY_COMPLETED = "CANNOT_MODIFY_COMPLETED"
