"""initial_migration

Revision ID: 1ba816e47e69
Revises: 
Create Date: 2025-12-25 00:07:45.638863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba816e47e69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('opening_hours', sa.String(length=255), nullable=True),
    sa.Column('contact_info', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('osm_id', sa.String(length=50), nullable=True),
    sa.Column('osm_type', sa.String(length=20), nullable=True),
    sa.Column('osm_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('destinations_pkey'))
    )
    op.create_index(op.f('destinations_category_idx'), 'destinations', ['category'], unique=False)
    op.create_index(op.f('destinations_id_idx'), 'destinations', ['id'], unique=False)
    op.create_index(op.f('destinations_name_idx'), 'destinations', ['name'], unique=False)
    op.create_index(op.f('destinations_osm_id_idx'), 'destinations', ['osm_id'], unique=False)
    op.create_index(op.f('destinations_source_idx'), 'destinations', ['source'], unique=False)
    op.create_table('popular_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('first_searched', sa.DateTime(), nullable=False),
    sa.Column('last_searched', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('popular_searches_pkey'))
    )
    op.create_index(op.f('popular_searches_id_idx'), 'popular_searches', ['id'], unique=False)
    op.create_index(op.f('popular_searches_query_idx'), 'popular_searches', ['query'], unique=False)
    op.create_index(op.f('popular_searches_search_type_idx'), 'popular_searches', ['search_type'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('search_history_pkey'))
    )
    op.create_index(op.f('search_history_id_idx'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('search_history_timestamp_idx'), 'search_history', ['timestamp'], unique=False)
    op.create_index(op.f('search_history_user_id_idx'), 'search_history', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey'))
    )
    op.create_index(op.f('tags_id_idx'), 'tags', ['id'], unique=False)
    op.create_index(op.f('tags_name_idx'), 'tags', ['name'], unique=True)
    op.create_index(op.f('tags_slug_idx'), 'tags', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_id_idx'), 'users', ['id'], unique=False)
    op.create_table('destination_tags',
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('destination_tags_destination_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('destination_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('destination_id', 'tag_id', name=op.f('destination_tags_pkey'))
    )
    op.create_table('favorite_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('favorite_destinations_destination_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('favorite_destinations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_destinations_pkey'))
    )
    op.create_index(op.f('favorite_destinations_id_idx'), 'favorite_destinations', ['id'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('destination_country', sa.String(length=100), nullable=True),
    sa.Column('destination_city', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('actual_cost', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('copy_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('itineraries_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('itineraries_pkey'))
    )
    op.create_index(op.f('itineraries_id_idx'), 'itineraries', ['id'], unique=False)
    op.create_index(op.f('itineraries_is_public_idx'), 'itineraries', ['is_public'], unique=False)
    op.create_index(op.f('itineraries_status_idx'), 'itineraries', ['status'], unique=False)
    op.create_index(op.f('itineraries_user_id_idx'), 'itineraries', ['user_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('media_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('media_pkey'))
    )
    op.create_index(op.f('media_entity_id_idx'), 'media', ['entity_id'], unique=False)
    op.create_index(op.f('media_entity_type_idx'), 'media', ['entity_type'], unique=False)
    op.create_index(op.f('media_id_idx'), 'media', ['id'], unique=False)
    op.create_index(op.f('media_user_id_idx'), 'media', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('reviews_destination_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reviews_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey'))
    )
    op.create_index(op.f('reviews_destination_id_idx'), 'reviews', ['destination_id'], unique=False)
    op.create_index(op.f('reviews_id_idx'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('reviews_user_id_idx'), 'reviews', ['user_id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_avg', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('weather_destination_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('weather_pkey'))
    )
    op.create_index(op.f('weather_date_idx'), 'weather', ['date'], unique=False)
    op.create_index(op.f('weather_destination_id_idx'), 'weather', ['destination_id'], unique=False)
    op.create_index(op.f('weather_id_idx'), 'weather', ['id'], unique=False)
    op.create_table('accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_per_night', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('accommodations_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('accommodations_pkey'))
    )
    op.create_index(op.f('accommodations_id_idx'), 'accommodations', ['id'], unique=False)
    op.create_index(op.f('accommodations_itinerary_id_idx'), 'accommodations', ['itinerary_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('actual_cost', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('activities_destination_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('activities_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activities_pkey'))
    )
    op.create_index(op.f('activities_id_idx'), 'activities', ['id'], unique=False)
    op.create_index(op.f('activities_itinerary_id_idx'), 'activities', ['itinerary_id'], unique=False)
    op.create_table('budget_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_percentage', sa.Float(), nullable=True),
    sa.Column('threshold_amount', sa.Integer(), nullable=True),
    sa.Column('total_budget', sa.Integer(), nullable=False),
    sa.Column('current_spent', sa.Integer(), nullable=False),
    sa.Column('remaining_budget', sa.Integer(), nullable=False),
    sa.Column('percentage_used', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('budget_alerts_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('budget_alerts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('budget_alerts_pkey'))
    )
    op.create_index(op.f('budget_alerts_id_idx'), 'budget_alerts', ['id'], unique=False)
    op.create_index(op.f('budget_alerts_itinerary_id_idx'), 'budget_alerts', ['itinerary_id'], unique=False)
    op.create_index(op.f('budget_alerts_user_id_idx'), 'budget_alerts', ['user_id'], unique=False)
    op.create_table('budget_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('current_cost', sa.Integer(), nullable=True),
    sa.Column('suggested_cost', sa.Integer(), nullable=True),
    sa.Column('potential_savings', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('alternative_options', sa.Text(), nullable=True),
    sa.Column('impact_analysis', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('is_viewed', sa.Boolean(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('budget_recommendations_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('budget_recommendations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('budget_recommendations_pkey'))
    )
    op.create_index(op.f('budget_recommendations_id_idx'), 'budget_recommendations', ['id'], unique=False)
    op.create_index(op.f('budget_recommendations_itinerary_id_idx'), 'budget_recommendations', ['itinerary_id'], unique=False)
    op.create_index(op.f('budget_recommendations_user_id_idx'), 'budget_recommendations', ['user_id'], unique=False)
    op.create_table('favorite_itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('favorite_itineraries_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('favorite_itineraries_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_itineraries_pkey'))
    )
    op.create_index(op.f('favorite_itineraries_id_idx'), 'favorite_itineraries', ['id'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('departure_city', sa.String(length=100), nullable=True),
    sa.Column('arrival_city', sa.String(length=100), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('flights_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('flights_pkey'))
    )
    op.create_index(op.f('flights_id_idx'), 'flights', ['id'], unique=False)
    op.create_index(op.f('flights_itinerary_id_idx'), 'flights', ['itinerary_id'], unique=False)
    op.create_table('itinerary_tags',
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('itinerary_tags_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('itinerary_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itinerary_id', 'tag_id', name=op.f('itinerary_tags_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('notifications_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('notifications_id_idx'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('notifications_is_read_idx'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('notifications_user_id_idx'), 'notifications', ['user_id'], unique=False)
    op.create_table('transportations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('transport_type', sa.String(length=50), nullable=False),
    sa.Column('from_location', sa.String(length=200), nullable=False),
    sa.Column('to_location', sa.String(length=200), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=150), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('transportations_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transportations_pkey'))
    )
    op.create_index(op.f('transportations_id_idx'), 'transportations', ['id'], unique=False)
    op.create_index(op.f('transportations_itinerary_id_idx'), 'transportations', ['itinerary_id'], unique=False)
    op.create_table('weather_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('weather_condition', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('precipitation_chance', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('alternative_dates', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('affected_activities', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('weather_alerts_destination_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('weather_alerts_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('weather_alerts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('weather_alerts_pkey'))
    )
    op.create_index(op.f('weather_alerts_id_idx'), 'weather_alerts', ['id'], unique=False)
    op.create_index(op.f('weather_alerts_itinerary_id_idx'), 'weather_alerts', ['itinerary_id'], unique=False)
    op.create_index(op.f('weather_alerts_user_id_idx'), 'weather_alerts', ['user_id'], unique=False)
    op.create_table('weather_based_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_condition', sa.String(length=100), nullable=True),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('weather_condition', sa.String(length=100), nullable=False),
    sa.Column('suitability_score', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('alternative_suggestion', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_model_version', sa.String(length=20), nullable=True),
    sa.Column('is_viewed', sa.Boolean(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('weather_based_recommendations_destination_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('weather_based_recommendations_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('weather_based_recommendations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('weather_based_recommendations_pkey'))
    )
    op.create_index(op.f('weather_based_recommendations_id_idx'), 'weather_based_recommendations', ['id'], unique=False)
    op.create_index(op.f('weather_based_recommendations_itinerary_id_idx'), 'weather_based_recommendations', ['itinerary_id'], unique=False)
    op.create_index(op.f('weather_based_recommendations_user_id_idx'), 'weather_based_recommendations', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('expenses_activity_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('expenses_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('expenses_pkey'))
    )
    op.create_index(op.f('expenses_id_idx'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('expenses_itinerary_id_idx'), 'expenses', ['itinerary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('expenses_itinerary_id_idx'), table_name='expenses')
    op.drop_index(op.f('expenses_id_idx'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('weather_based_recommendations_user_id_idx'), table_name='weather_based_recommendations')
    op.drop_index(op.f('weather_based_recommendations_itinerary_id_idx'), table_name='weather_based_recommendations')
    op.drop_index(op.f('weather_based_recommendations_id_idx'), table_name='weather_based_recommendations')
    op.drop_table('weather_based_recommendations')
    op.drop_index(op.f('weather_alerts_user_id_idx'), table_name='weather_alerts')
    op.drop_index(op.f('weather_alerts_itinerary_id_idx'), table_name='weather_alerts')
    op.drop_index(op.f('weather_alerts_id_idx'), table_name='weather_alerts')
    op.drop_table('weather_alerts')
    op.drop_index(op.f('transportations_itinerary_id_idx'), table_name='transportations')
    op.drop_index(op.f('transportations_id_idx'), table_name='transportations')
    op.drop_table('transportations')
    op.drop_index(op.f('notifications_user_id_idx'), table_name='notifications')
    op.drop_index(op.f('notifications_is_read_idx'), table_name='notifications')
    op.drop_index(op.f('notifications_id_idx'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('itinerary_tags')
    op.drop_index(op.f('flights_itinerary_id_idx'), table_name='flights')
    op.drop_index(op.f('flights_id_idx'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('favorite_itineraries_id_idx'), table_name='favorite_itineraries')
    op.drop_table('favorite_itineraries')
    op.drop_index(op.f('budget_recommendations_user_id_idx'), table_name='budget_recommendations')
    op.drop_index(op.f('budget_recommendations_itinerary_id_idx'), table_name='budget_recommendations')
    op.drop_index(op.f('budget_recommendations_id_idx'), table_name='budget_recommendations')
    op.drop_table('budget_recommendations')
    op.drop_index(op.f('budget_alerts_user_id_idx'), table_name='budget_alerts')
    op.drop_index(op.f('budget_alerts_itinerary_id_idx'), table_name='budget_alerts')
    op.drop_index(op.f('budget_alerts_id_idx'), table_name='budget_alerts')
    op.drop_table('budget_alerts')
    op.drop_index(op.f('activities_itinerary_id_idx'), table_name='activities')
    op.drop_index(op.f('activities_id_idx'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('accommodations_itinerary_id_idx'), table_name='accommodations')
    op.drop_index(op.f('accommodations_id_idx'), table_name='accommodations')
    op.drop_table('accommodations')
    op.drop_index(op.f('weather_id_idx'), table_name='weather')
    op.drop_index(op.f('weather_destination_id_idx'), table_name='weather')
    op.drop_index(op.f('weather_date_idx'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('reviews_user_id_idx'), table_name='reviews')
    op.drop_index(op.f('reviews_id_idx'), table_name='reviews')
    op.drop_index(op.f('reviews_destination_id_idx'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('media_user_id_idx'), table_name='media')
    op.drop_index(op.f('media_id_idx'), table_name='media')
    op.drop_index(op.f('media_entity_type_idx'), table_name='media')
    op.drop_index(op.f('media_entity_id_idx'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('itineraries_user_id_idx'), table_name='itineraries')
    op.drop_index(op.f('itineraries_status_idx'), table_name='itineraries')
    op.drop_index(op.f('itineraries_is_public_idx'), table_name='itineraries')
    op.drop_index(op.f('itineraries_id_idx'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('favorite_destinations_id_idx'), table_name='favorite_destinations')
    op.drop_table('favorite_destinations')
    op.drop_table('destination_tags')
    op.drop_index(op.f('users_id_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('tags_slug_idx'), table_name='tags')
    op.drop_index(op.f('tags_name_idx'), table_name='tags')
    op.drop_index(op.f('tags_id_idx'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('search_history_user_id_idx'), table_name='search_history')
    op.drop_index(op.f('search_history_timestamp_idx'), table_name='search_history')
    op.drop_index(op.f('search_history_id_idx'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('popular_searches_search_type_idx'), table_name='popular_searches')
    op.drop_index(op.f('popular_searches_query_idx'), table_name='popular_searches')
    op.drop_index(op.f('popular_searches_id_idx'), table_name='popular_searches')
    op.drop_table('popular_searches')
    op.drop_index(op.f('destinations_source_idx'), table_name='destinations')
    op.drop_index(op.f('destinations_osm_id_idx'), table_name='destinations')
    op.drop_index(op.f('destinations_name_idx'), table_name='destinations')
    op.drop_index(op.f('destinations_id_idx'), table_name='destinations')
    op.drop_index(op.f('destinations_category_idx'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
