# User name constraints
MIN_NAME_LENGTH = 1
MAX_NAME_LENGTH = 100


class ErrorCode:
    # User errors
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INACTIVE_USER = "INACTIVE_USER"
    
    # Profile errors
    INVALID_NAME_LENGTH = "INVALID_NAME_LENGTH"
    PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED"
    
    # Password errors
    INCORRECT_OLD_PASSWORD = "INCORRECT_OLD_PASSWORD"
    PASSWORD_CHANGE_FAILED = "PASSWORD_CHANGE_FAILED"
    SAME_PASSWORD = "SAME_PASSWORD"
    
    # Account errors
    ACCOUNT_DELETION_FAILED = "ACCOUNT_DELETION_FAILED"
